const PERMISSIONS = {
  CREATE_USER: "PERMISSION_CREATE_USER"
};
const FIRST_USER_PASSWORD = "123";
const FIRST_USER_EMAIL = "email@email.com";

export {
  PERMISSIONS,
  FIRST_USER_PASSWORD,
  FIRST_USER_EMAIL,
};
